# Configuration for Binance WebSocket Real Connection
# Copy to src/main/resources/application-binance.yml to use

websocket:
  exchange: BINANCE
  url: wss://stream.binance.com:9443/stream?streams=btcusdt@ticker/btcusdc@ticker/usdcusdt@ticker  # Specific BTC and USDC pairs only
  connection-timeout: 30s
  read-timeout: 10s
  max-retries: 10
  retry-interval: 5s
  auto-reconnect: true



# For testnet (if available)
# websocket:
#   url: wss://testnet.binance.vision/ws/!ticker@arr