# Configuration for Binance WebSocket Real Connection
# Copy to src/main/resources/application-binance.yml to use

websocket:
  exchange: BINANCE
  url: wss://stream.binance.com:9443/stream  # Base URL - streams will be added dynamically
  connection-timeout: 30s
  read-timeout: 10s
  max-retries: 10
  retry-interval: 5s
  auto-reconnect: true

trading:
  pairs:
    active:
      - BTCUSDT
      - ETHUSDT
    stream-format: ticker
