trading:
  strategies:
    auto-register: true
    max-concurrent-strategies: 10
    strategies:
      pair-trading-strategy:
        enabled: true
        priority: 1
        max-order-value: 1000
        min-order-value: 10
        parameters:
          pair1: "BTCUSDT"
          pair2: "ETHUSDT"
          upperThreshold: 1.0     # Muito mais sensível para gerar mais SELL signals
          lowerThreshold: -1.0    # Muito mais sensível para gerar mais BUY signals  
          maxHistorySize: 15      # Histórico ainda menor = mais reativo às mudanças
          tradingAmount: 100.0